#!/bin/bash

echo "🔍 Google OAuth Client Verification & Fix Script"
echo "=================================================="
echo ""
echo "This script will help you verify your OAuth setup and create new credentials if needed."
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "Step 1: Checking Current Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cd "$(dirname "$0")/auth-service"
source .env 2>/dev/null

CURRENT_CLIENT_ID="$GOOGLE_CLIENT_ID"
echo "Current Client ID: $CURRENT_CLIENT_ID"
echo ""

echo "Step 2: What You Need to Do in Google Cloud Console"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Open this link in your browser:"
echo "   ${YELLOW}https://console.cloud.google.com/apis/credentials${NC}"
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1️⃣  CHECK WHICH PROJECT IS SELECTED"
echo "   - Look at the top of the page"
echo "   - You should see the project name"
echo "   - Make sure it's YOUR project (e.g., 'LMS Authentication')"
echo ""
echo "2️⃣  LOOK FOR YOUR OAUTH CLIENT ID"
echo "   - In the 'OAuth 2.0 Client IDs' section"
echo "   - Do you see an entry like 'LMS Web Client' or similar?"
echo ""
echo "   ${GREEN}✅ If YES:${NC}"
echo "      - Click on it"
echo "      - Check if the Client ID matches: $CURRENT_CLIENT_ID"
echo "      - If it matches, the problem might be:"
echo "        • Google propagation delay (wait 10-15 minutes)"
echo "        • Browser cache (use incognito mode)"
echo ""
echo "   ${RED}❌ If NO (or Client ID doesn't match):${NC}"
echo "      - Your OAuth client was actually deleted OR"
echo "      - You're looking at the wrong project OR"
echo "      - The client never existed"
echo "      → You need to create a NEW OAuth client!"
echo ""
echo "3️⃣  TO CREATE NEW OAUTH CLIENT:"
echo "   a) Click '+ CREATE CREDENTIALS' button at the top"
echo "   b) Select 'OAuth client ID'"
echo "   c) If prompted to configure consent screen, click 'CONFIGURE CONSENT SCREEN'"
echo ""
echo "4️⃣  CONFIGURE CONSENT SCREEN (if needed):"
echo "   - User Type: External"
echo "   - App name: LMS Application"
echo "   - User support email: your email"
echo "   - Developer contact: your email"
echo "   - Click 'SAVE AND CONTINUE'"
echo "   - Scopes: Add email, profile, openid"
echo "   - Click 'SAVE AND CONTINUE'"
echo "   - Test users: Add your Gmail address"
echo "   - Click 'SAVE AND CONTINUE'"
echo "   - Click 'BACK TO DASHBOARD'"
echo ""
echo "5️⃣  CREATE THE OAUTH CLIENT:"
echo "   - Go back to Credentials → '+ CREATE CREDENTIALS' → 'OAuth client ID'"
echo "   - Application type: Web application"
echo "   - Name: LMS Web Client"
echo ""
echo "   ${YELLOW}Authorized JavaScript origins (click ADD URI for each):${NC}"
echo "   ┌──────────────────────────────────────┐"
echo "   │ http://localhost:5173                │"
echo "   │ http://localhost:5174                │"
echo "   │ http://localhost:1001                │"
echo "   │ http://localhost:1002                │"
echo "   └──────────────────────────────────────┘"
echo ""
echo "   ${YELLOW}Authorized redirect URIs (click ADD URI for each):${NC}"
echo "   ┌──────────────────────────────────────────────────────────┐"
echo "   │ http://localhost:1002/api/auth/google/callback           │"
echo "   │ http://localhost:5173/auth/callback                      │"
echo "   └──────────────────────────────────────────────────────────┘"
echo ""
echo "   - Click 'CREATE'"
echo ""
echo "6️⃣  COPY THE CREDENTIALS:"
echo "   - A popup will show your Client ID and Secret"
echo "   - ${GREEN}Copy the Client ID${NC} (looks like: 123456-abc...xyz.apps.googleusercontent.com)"
echo "   - ${GREEN}Copy the Client Secret${NC} (looks like: GOCSPX-abc...xyz)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 After you have the NEW credentials:"
echo ""
echo "1. Edit the backend .env file:"
echo "   nano /home/spade/Public/Repository/MERN_FREELANCE/server/auth-service/.env"
echo ""
echo "2. Update these lines with YOUR new credentials:"
echo "   ${YELLOW}GOOGLE_CLIENT_ID=paste_your_new_client_id_here${NC}"
echo "   ${YELLOW}GOOGLE_CLIENT_SECRET=paste_your_new_client_secret_here${NC}"
echo ""
echo "3. Edit the frontend .env file:"
echo "   nano /home/spade/Public/Repository/MERN_FREELANCE/client/.env"
echo ""
echo "4. Update this line with the SAME client ID:"
echo "   ${YELLOW}VITE_GOOGLE_CLIENT_ID=paste_your_new_client_id_here${NC}"
echo ""
echo "5. Restart services:"
echo "   cd /home/spade/Public/Repository/MERN_FREELANCE/server"
echo "   ./stop-all.sh"
echo "   ./start-all.sh"
echo ""
echo "6. Restart frontend:"
echo "   cd /home/spade/Public/Repository/MERN_FREELANCE/client"
echo "   # Stop with Ctrl+C, then:"
echo "   npm run dev"
echo ""
echo "7. ${RED}IMPORTANT:${NC} Wait 10 minutes for Google to propagate the new credentials!"
echo ""
echo "8. Clear browser cache or use incognito mode"
echo ""
echo "9. Test: http://localhost:5173/login"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔥 QUICK FIX for testing right now:"
echo ""
echo "If you want to test authentication without Google OAuth:"
echo "1. Use regular email/password login"
echo "2. Comment out Google OAuth button in Login.jsx temporarily"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "${GREEN}Need help? Check these files:${NC}"
echo "- /GOOGLE_OAUTH_CREDENTIALS_FIX.md"
echo "- /OAUTH_CLIENT_DELETED_FIX.md"
echo "- /GOOGLE_AUTH_RECAPTCHA_SETUP.md"
echo ""
